// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoologico.API.Context;

#nullable disable

namespace Zoologico.API.Migrations
{
    [DbContext(typeof(ZoologicoContext))]
    [Migration("20250411110444_CriacaoTabelas")]
    partial class CriacaoTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalModelCuidadoModel", b =>
                {
                    b.Property<int>("Animaisid")
                        .HasColumnType("int");

                    b.Property<int>("Cuidadosid")
                        .HasColumnType("int");

                    b.HasKey("Animaisid", "Cuidadosid");

                    b.HasIndex("Cuidadosid");

                    b.ToTable("AnimalModelCuidadoModel");
                });

            modelBuilder.Entity("Zoologico.API.Models.AnimalModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dthNascimento")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Zoologico.API.Models.CuidadoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCuidado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cuidados");
                });

            modelBuilder.Entity("AnimalModelCuidadoModel", b =>
                {
                    b.HasOne("Zoologico.API.Models.AnimalModel", null)
                        .WithMany()
                        .HasForeignKey("Animaisid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoologico.API.Models.CuidadoModel", null)
                        .WithMany()
                        .HasForeignKey("Cuidadosid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
